<!-- The top of file index.html -->
<html itemscope itemtype="http://schema.org/Article">
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
    </script>
</head>
<body>

<?php
                require '/../../../../vendor/autoload.php';
                if(!isset($_SESSION))
                   {
                       session_start();
                   }
                 $client = new Google_Client();
                 $client->setClientId('51037973777-2i03a7rmfhlbme4cr518o1mq8661s5fo.apps.googleusercontent.com');
                 $client->setClientSecret('Zp87u9QXHEONlEsZlWsCQxgm');
                 $client->setRedirectUri('http://localhost/411/phalcon/public/home');
                 $client->addScope("email");
                 $client->addScope("profile");

                 $service = new Google_Service_Oauth2($client);
                 if (isset($_GET['code'])) {
                        $client->authenticate($_GET['code']);
                        $_SESSION['access_token'] = $client->getAccessToken();
                        header('Location: ' . filter_var('http://localhost/411/phalcon/public/home', FILTER_SANITIZE_URL));
                        exit;
                    }
                 if (isset($_REQUEST['logout'])) {
                        unset($_SESSION['access_token']);
                     header('Location: https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF']);
                 }


                if (isset($_SESSION['access_token']) && $_SESSION['access_token']) {
                        $client->setAccessToken($_SESSION['access_token']);
                   } else {
                        $authUrl = $client->createAuthUrl('http://localhost/411/phalcon/public/home');
                    }

                         echo '<div style="margin:20px">';
                         if (isset($authUrl)){

                                echo '<div align="center">';
                             echo '<h3>Welcome to 411 project!</h3>';
                             echo '<div>Please click login button to connect to Google!</div>';
                             echo "<a class='btn btn-default btn-outline btn-circle collapsed' href=  $authUrl >Sign In</a>";
                            echo '</div>';

                         }else{

                            $userInfo = $service->userinfo->get(); //get user info
                            $id=$userInfo->id;
                            $user = Users::findFirst($id);


                             echo "Welcome back, $userInfo->name ";
                             echo"</br>";
                             echo "Client Id:".$id;

                    }
?>
</body>
</html>